package com.archivist;

import com.google.gson.*;
import net.fabricmc.loader.api.FabricLoader;

import java.io.*;
import java.nio.file.*;
import java.util.*;

public class PluginGlossary {

    private static final Path DICT_PATH =
            FabricLoader.getInstance().getConfigDir().resolve("archivist-glossary.json");

    private final Map<String, String> entries = new LinkedHashMap<>();

    private static final List<Map.Entry<String, String>> DEFAULT_ENTRIES = List.of(
        //ADD AS MANY AS YOU WANT TO
            Map.entry("lp",                    "luckperms"),
            Map.entry("luckperms",             "luckperms"),
            Map.entry("pex",                   "permissionsex"),
            Map.entry("permissionsex",         "permissionsex"),
            Map.entry("ess",                   "essentialsx"),
            Map.entry("essentials",            "essentialsx"),
            Map.entry("essentialsx",           "essentialsx"),
            Map.entry("vault",                 "vault"),
            Map.entry("we",                    "worldedit"),
            Map.entry("worldedit",             "worldedit"),
            Map.entry("wg",                    "worldguard"),
            Map.entry("worldguard",            "worldguard"),
            Map.entry("co",                    "coreprotect"),
            Map.entry("coreprotect",           "coreprotect"),
            Map.entry("dynmap",                "dynmap"),
            Map.entry("via",                   "viaversion"),
            Map.entry("viaversion",            "viaversion"),
            Map.entry("vb",                    "viabackwards"),
            Map.entry("viabackwards",          "viabackwards"),
            Map.entry("skript",                "skript"),
            Map.entry("mv",                    "multiverse-core"),
            Map.entry("multiverse",            "multiverse-core"),
            Map.entry("papi",                  "placeholderapi"),
            Map.entry("placeholderapi",        "placeholderapi"),
            Map.entry("npc",                   "citizens"),
            Map.entry("citizens",              "citizens"),
            Map.entry("mythicmobs",            "mythicmobs"),
            Map.entry("myth",                  "mythicmobs"),
            Map.entry("plot",                  "plotsquared"),
            Map.entry("plots",                 "plotsquared"),
            Map.entry("plotsquared",           "plotsquared"),
            Map.entry("gp",                    "griefprevention"),
            Map.entry("griefprevention",       "griefprevention"),
            Map.entry("towny",                 "towny"),
            Map.entry("factions",              "factions"),
            Map.entry("lands",                 "lands"),
            Map.entry("authme",                "authme"),
            Map.entry("protocollib",           "protocollib"),
            Map.entry("packetevents",          "packetevents"),
            Map.entry("litebans",              "litebans"),
            Map.entry("advancedban",           "advancedban"),
            Map.entry("ncp",                   "nocheatplus"),
            Map.entry("nocheatplus",           "nocheatplus"),
            Map.entry("spartan",               "spartan"),
            Map.entry("matrix",                "matrix anticheat"),
            Map.entry("aac",                   "antiaura"),
            Map.entry("jobs",                  "jobs reborn"),
            Map.entry("job",                   "jobs reborn"),
            Map.entry("quests",                "quests"),
            Map.entry("mcmmo",                 "mcmmo"),
            Map.entry("itemsadder",            "itemsadder"),
            Map.entry("ia",                    "itemsadder"),
            Map.entry("oraxen",                "oraxen"),
            Map.entry("nexo",                  "nexo"),
            Map.entry("cmi",                   "cmi"),
            Map.entry("tab",                   "tab"),
            Map.entry("chunky",                "chunky"),
            Map.entry("spark",                 "spark"),
            Map.entry("clearlag",              "clearlag"),
            Map.entry("geyser",                "geyser"),
            Map.entry("floodgate",             "floodgate"),
            Map.entry("deluxemenu",            "deluxemenus"),
            Map.entry("deluxemenus",           "deluxemenus"),
            Map.entry("dm",                    "deluxemenus"),
            Map.entry("shopguiplus",           "shopgui+"),
            Map.entry("pp",                    "playerpoints"),
            Map.entry("playerpoints",          "playerpoints"),
            Map.entry("modelengine",           "modelengine"),
            Map.entry("mmoitems",              "mmoitems"),
            Map.entry("advancedenchantments",  "advancedenchantments"),
            Map.entry("veinminer",             "veinminer"),
            Map.entry("treecapitator",         "treecapitator"),
            Map.entry("chestsort",             "chestsort"),
            Map.entry("bungeeguard",           "bungeeguard"),
            Map.entry("chatcontrol",           "chatcontrol"),
            Map.entry("antispam",              "antispam"),
            Map.entry("discord",               "discordsrv"),
            Map.entry("discordsrv",            "discordsrv"),
            Map.entry("vault",                     "vault"),
            Map.entry("we",                        "worldedit"),
            Map.entry("worldedit",                 "worldedit"),
            Map.entry("wg",                        "worldguard"),
            Map.entry("worldguard",                "worldguard"),
            Map.entry("co",                        "coreprotect"),
            Map.entry("coreprotect",               "coreprotect"),
            Map.entry("dynmap",                    "dynmap"),
            Map.entry("via",                       "viaversion"),
            Map.entry("viaversion",                "viaversion"),
            Map.entry("vb",                        "viabackwards"),
            Map.entry("viabackwards",              "viabackwards"),
            Map.entry("skript",                    "skript"),
            Map.entry("mv",                        "multiverse-core"),
            Map.entry("multiverse",                "multiverse-core"),
            Map.entry("papi",                      "placeholderapi"),
            Map.entry("placeholderapi",            "placeholderapi"),
            Map.entry("npc",                       "citizens"),
            Map.entry("citizens",                  "citizens"),
            Map.entry("mythicmobs",                "mythicmobs"),
            Map.entry("myth",                      "mythicmobs"),
            Map.entry("plot",                      "plotsquared"),
            Map.entry("plots",                     "plotsquared"),
            Map.entry("plotsquared",               "plotsquared"),
            Map.entry("gp",                        "griefprevention"),
            Map.entry("griefprevention",           "griefprevention"),
            Map.entry("towny",                     "towny"),
            Map.entry("factions",                  "factions"),
            Map.entry("lands",                     "lands"),
            Map.entry("authme",                    "authme"),
            Map.entry("protocollib",               "protocollib"),
            Map.entry("packetevents",              "packetevents"),
            Map.entry("litebans",                  "litebans"),
            Map.entry("advancedban",               "advancedban"),
            Map.entry("ncp",                       "nocheatplus"),
            Map.entry("nocheatplus",               "nocheatplus"),
            Map.entry("spartan",                   "spartan"),
            Map.entry("matrix",                    "matrix anticheat"),
            Map.entry("aac",                       "antiaura"),
            Map.entry("jobs",                      "jobs reborn"),
            Map.entry("job",                       "jobs reborn"),
            Map.entry("quests",                    "quests"),
            Map.entry("mcmmo",                     "mcmmo"),
            Map.entry("itemsadder",                "itemsadder"),
            Map.entry("ia",                        "itemsadder"),
            Map.entry("oraxen",                    "oraxen"),
            Map.entry("nexo",                      "nexo"),
            Map.entry("cmi",                       "cmi"),
            Map.entry("tab",                       "tab"),
            Map.entry("chunky",                    "chunky"),
            Map.entry("spark",                     "spark"),
            Map.entry("clearlag",                  "clearlag"),
            Map.entry("geyser",                    "geyser"),
            Map.entry("floodgate",                 "floodgate"),
            Map.entry("deluxemenu",                "deluxemenus"),
            Map.entry("deluxemenus",               "deluxemenus"),
            Map.entry("dm",                        "deluxemenus"),
            Map.entry("shopguiplus",               "shopgui+"),
            Map.entry("pp",                        "playerpoints"),
            Map.entry("playerpoints",              "playerpoints"),
            Map.entry("modelengine",               "modelengine"),
            Map.entry("mmoitems",                  "mmoitems"),
            Map.entry("advancedenchantments",      "advancedenchantments"),
            Map.entry("veinminer",                 "veinminer"),
            Map.entry("treecapitator",             "treecapitator"),
            Map.entry("chestsort",                 "chestsort"),
            Map.entry("bungeeguard",               "bungeeguard"),
            Map.entry("chatcontrol",               "chatcontrol"),
            Map.entry("antispam",                  "antispam"),
            Map.entry("discord",                   "discordsrv"),
            Map.entry("discordsrv",                "discordsrv"),
            Map.entry("excellentcrates",           "excellentcrates"),
            Map.entry("cc",                        "crazycrates"),
            Map.entry("crazycrates",               "crazycrates"),
            Map.entry("gc",                        "golden_crates"),
            Map.entry("sc",                        "specializedcrates"),
            Map.entry("cratesplus",                "cratesplus"),
            Map.entry("illegalstack",              "illegalstack"),
            Map.entry("dupeme",                    "dupeme"),
            Map.entry("dupe",                      "anydupe"),
            Map.entry("customitemdupe",            "itemduplicator"),
            Map.entry("vulcan",                    "vulcan anticheat"),
            Map.entry("grim",                      "grim anticheat"),
            Map.entry("carbon",                    "carbon chat"),
            Map.entry("pufferfish",                "pufferfish optimizer"),
            Map.entry("leaves",                    "leavesmc"),
            Map.entry("rosestacker",               "rosestacker"),
            Map.entry("executableitems",           "executableitems"),
            Map.entry("ei",                        "executableitems"),
            Map.entry("fancyholograms",            "fancyholograms"),
            Map.entry("vane",                      "vane rpg"),
            Map.entry("alonetoken",                "alonetoken"),
            Map.entry("venturechat",               "venturechat"),
            Map.entry("vc",                        "venturechat"),
            Map.entry("interactivechat",           "interactivechat"),
            Map.entry("ic",                        "interactivechat"),
            Map.entry("decors",                    "decors"),
            Map.entry("furniturelib",              "furniturelib"),
            Map.entry("dicefurniture",             "dicefurniture"),
            Map.entry("protectionstones",          "protectionstones"),
            Map.entry("ps",                        "protectionstones"),
            Map.entry("griefdefender",             "griefdefender"),
            Map.entry("gd",                        "griefdefender"),
            Map.entry("angelskills",               "angelskills"),
            Map.entry("procosmetics",              "procosmetics"),
            Map.entry("ultraeconomy",              "ultraeconomy"),
            Map.entry("ue",                        "ultraeconomy"),
            Map.entry("ultrapermissions",          "ultrapermissions"),
            Map.entry("up",                        "ultrapermissions"),
            Map.entry("ultracustomizer",           "ultracustomizer"),
            Map.entry("uc",                        "ultracustomizer"),
            Map.entry("mythiclib",                 "mythiclib"),
            Map.entry("mmoinventory",              "mmoinventory"),
            Map.entry("mmofactions",               "mmofactions"),
            Map.entry("mmocore",                   "mmocore"),
            Map.entry("phoenixway",                "phoenixway"),
            Map.entry("kixsautoannouncer",         "autoannouncer"),
            Map.entry("ajleaderboards",            "ajleaderboards"),
            Map.entry("ajlb",                      "ajleaderboards"),
            Map.entry("liteplayertracker",         "playertracker"),
            Map.entry("plan",                      "plan analytics"),
            Map.entry("bluemap",                   "bluemap"),
            Map.entry("squaremap",                 "squaremap"),
            Map.entry("pl3xmap",                   "squaremap"),
            Map.entry("freedomchat",               "freedomchat"),
            Map.entry("antimalware",               "antimalware"),
            Map.entry("spigotguard",               "spigotguard"),
            Map.entry("exploitfixer",              "exploitfixer"),
            Map.entry("ef",                        "exploitfixer"),
            Map.entry("lp-gui",                    "luckpermsgui"),
            Map.entry("huskperms",                 "huskperms"),
            Map.entry("huskshomes",                "huskhomes"),
            Map.entry("huskworld",                 "huskworld"),
            Map.entry("betterrtp",                 "betterrtp"),
            Map.entry("brtp",                      "betterrtp"),
            Map.entry("iris",                      "iris worldgen"),
            Map.entry("terralith",                 "terralith"),
            Map.entry("structuremodifier",         "structuremodifier"),
            Map.entry("worldmanager",              "worldmanager"),
            Map.entry("wm",                        "worldmanager"),
            Map.entry("slimeworldmanager",         "swm"),
            Map.entry("swm",                       "slimeworldmanager"),
            Map.entry("advancedregionmarket",      "arm"),
            Map.entry("arm",                       "advancedregionmarket"),
            Map.entry("bentobox",                  "bentobox"),
            Map.entry("bskyblock",                 "bskyblock"),
            Map.entry("acidisland",                "acidisland"),
            Map.entry("superiorkyblock",           "superiorskyblock"),
            Map.entry("fabledskyblock",            "fabledskyblock"),
            Map.entry("iridiumskyblock",           "iridiumskyblock"),
            Map.entry("auctionhouse",              "auctionhouse"),
            Map.entry("zauctionhouse",             "zauctionhouse"),
            Map.entry("ezauctionhouse",            "ezauctionhouse"),
            Map.entry("dailyrewards",              "dailyrewards"),
            Map.entry("dr",                        "dailyrewards"),
            Map.entry("liteannouncer",             "liteannouncer"),
            Map.entry("playerglow",                "playerglow"),
            Map.entry("tablist",                   "tablist"),
            Map.entry("tl",                        "tablist"),
            Map.entry("animatednames",             "animatednames"),
            Map.entry("an",                        "animatednames"),
            Map.entry("nametagedit",               "nametagedit"),
            Map.entry("nte",                       "nametagedit"),
            Map.entry("skinsrestorer",             "skinsrestorer"),
            Map.entry("sr",                        "skinsrestorer"),
            Map.entry("petmaster",                 "petmaster"),
            Map.entry("mypet",                     "mypet"),
            Map.entry("minipets",                  "minipets"),
            Map.entry("ultrapets",                 "ultrapets"),
            Map.entry("modeldata",                 "custommodeldata"),
            Map.entry("cmd",                       "custommodeldata"),
            Map.entry("resourcepack",              "resourcepackmanager"),
            Map.entry("rpm",                       "resourcepackmanager"),
            Map.entry("forcepack",                 "forcepack"),
            Map.entry("itemsnatcher",              "itemsnatcher"),
            Map.entry("itemedit",                  "itemedit"),
            Map.entry("ie",                        "itemedit"),
            Map.entry("customcrafting",            "customcrafting"),
            Map.entry("ccraft",                    "customcrafting"),
            Map.entry("advancedrecipes",           "advancedrecipes"),
            Map.entry("ar",                        "advancedrecipes"),
            Map.entry("epicspawners",              "epicspawners"),
            Map.entry("wildstacker",               "wildstacker"),
            Map.entry("ws",                        "wildstacker"),
            Map.entry("mergestack",                "mergestack"),
            Map.entry("mobstacker",                "mobstacker"),
            Map.entry("ms",                        "mobstacker"),
            Map.entry("condense",                  "condense"),
            Map.entry("sellgui",                   "sellgui"),
            Map.entry("chunkloader",               "chunkloader"),
            Map.entry("cl",                        "chunkloader"),
            Map.entry("fastchunkpregenerator",     "fcp"),
            Map.entry("fcp",                       "fastchunkpregenerator"),
            Map.entry("serverrestorer",            "serverrestorer"),
            Map.entry("backup",                    "backup"),
            Map.entry("easybackup",                "easybackup"),
            Map.entry("eb",                        "easybackup"),
            Map.entry("donutcore",                 "donutsmp-core"),
            Map.entry("dcore",                     "donutsmp-core"),
            Map.entry("dsettings",                 "donutsmp-core"),
            Map.entry("donutadmin",                "donutsmp-core"),
            Map.entry("shard",                     "donutsmp-shards"),
            Map.entry("shards",                    "donutsmp-shards"),
            Map.entry("shardshop",                 "donutsmp-shards"),
            Map.entry("setshard",                  "donutsmp-shards"),
            Map.entry("giveshard",                 "donutsmp-shards"),
            Map.entry("donutshop",                 "donutsmp-core"),
            Map.entry("donutorder",                "donutorder"),
            Map.entry("vieworder",                 "donutorder"),
            Map.entry("donutcrate",                "donutcrates"),
            Map.entry("dcrates",                   "donutcrates"),
            Map.entry("cratekey",                  "donutcrates"),
            Map.entry("donutduel",                 "donutduels"),
            Map.entry("dduel",                     "donutduels"),
            Map.entry("acceptduel",                "donutduels"),
            Map.entry("donutecon",                 "donutsmp-economy"),
            Map.entry("decon",                     "donutsmp-economy"),
            Map.entry("donutessentials",           "donutessentials"),
            Map.entry("dessentials",               "donutessentials"),
            Map.entry("donutpunish",               "donutessentials"),
            Map.entry("drill",                     "donutdrillx"),
            Map.entry("drillgive",                 "donutdrillx"),
            Map.entry("smartspawner",              "smartspawners"),
            Map.entry("sspawner",                  "smartspawners"),
            Map.entry("spawnergui",                "smartspawners"),
            Map.entry("donuthome",                 "donutsmp-homes"),
            Map.entry("homesgui",                  "donutsmp-homes"),
            Map.entry("lifestealrevive",           "donut-revive"),
            Map.entry("revivetoken",               "donut-revive"),
            Map.entry("withdrawheart",             "lifesteal-core"),
            Map.entry("heartitem",                 "lifesteal-core"),
            Map.entry("seedshield",                "seedshield"),
            Map.entry("pa",                        "playerauction"),
            Map.entry("playerauction",             "playerauction"),
            Map.entry("axtrade",                   "axtrade"),
            Map.entry("irp",                       "inventoryrollbackplus"),
            Map.entry("inventoryrollback",         "inventoryrollbackplus"),
            Map.entry("inventoryrollbackplus",     "inventoryrollbackplus"),
            Map.entry("pk",                        "playerkits"),
            Map.entry("playerkits",                "playerkits"),
            Map.entry("pk2",                       "playerkits2"),
            Map.entry("playerkits2",               "playerkits2"),
            Map.entry("themis",                    "themis"),
            Map.entry("nightcore",                 "nightcore"),
            Map.entry("coinsengine",               "coinsengine"),
            Map.entry("lsz",                       "lifestealz"),
            Map.entry("lifestealz",                "lifestealz"),
            Map.entry("shopkeeper",                "shopkeepers"),
            Map.entry("shopkeepers",               "shopkeepers"),
            Map.entry("esgui",                     "economyshopgui-market"),
            Map.entry("economyshopgui",            "economyshopgui-market")
    );

    public void load() {
        entries.clear();
        if (!Files.exists(DICT_PATH)) {
            // First run: seed with defaults then persist
            for (Map.Entry<String, String> e : DEFAULT_ENTRIES) {
                entries.put(e.getKey(), e.getValue());
            }
            save();
            return;
        }

        try (Reader r = Files.newBufferedReader(DICT_PATH)) {
            JsonObject obj = JsonParser.parseReader(r).getAsJsonObject();
            if (obj.has("entries")) {
                JsonObject entriesObj = obj.getAsJsonObject("entries");
                for (Map.Entry<String, JsonElement> e : entriesObj.entrySet()) {
                    if (e.getValue().isJsonPrimitive()) {
                        entries.put(e.getKey(), e.getValue().getAsString());
                    }
                }
            }
        } catch (Exception e) {
            ArchivistMod.LOGGER.warn("[Archivist] Failed to load glossary: {}", e.getMessage());
            ArchivistMod.sendMessage("Failed to load glossary: " + e.getMessage());
        }
    }

    public void save() {
        try {
            JsonObject root = new JsonObject();
            JsonObject entriesObj = new JsonObject();
            entries.forEach(entriesObj::addProperty);
            root.add("entries", entriesObj);
            Files.writeString(DICT_PATH, new GsonBuilder().setPrettyPrinting().create().toJson(root));
        } catch (Exception e) {
            ArchivistMod.sendMessage("Failed to save glossary: " + e.getMessage());
        }
    }

    public String lookup(String command) {
        return entries.get(command.toLowerCase());
    }

    public void setEntries(Map<String, String> newEntries) {
        entries.clear();
        entries.putAll(newEntries);
    }

    public Map<String, String> getEntries() {
        return Collections.unmodifiableMap(entries);
    }

}
